create table
  public.diff (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    constraint diff_pkey primary key (id)
  ) tablespace pg_default;